version: '3'

volumes:
  pgdata:
services:

  python: &python

    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: bash "./docker_entrypoint.sh"
    depends_on:
      - postgres
      - rabbitmq
      - celery_worker

  postgres:
    image: postgres:10.3
    env_file:
      - config/db/database_env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432



  rabbitmq:
    image: rabbitmq:3.7-alpine

  celery_worker:
    <<: *python
    command: celery -A kamping worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - postgres