# Generated by Django 2.2.4 on 2019-09-07 14:30

import camp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('starter_time', models.TimeField(null=True, verbose_name='Başlangıç saati')),
                ('starter_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç günü')),
                ('size', models.IntegerField(default=0, null=True, verbose_name='Katılımcı sayısı')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Lokasyon')),
                ('category', models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('diğer', 'DİĞER'), ('yazılım', 'YAZILIM'), ('grafik tasarım', 'GRAFIK TASARIM')], max_length=53, null=True, verbose_name='Kategori')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, default='default/default.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=camp.models.upload_to, verbose_name='Resim')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='CampParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('camp', models.ForeignKey(null=True, on_delete=True, related_name='camp_participants', to='camp.Camp')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='camp_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kampa gelen katılımcılar',
            },
        ),
    ]
