# Generated by Django 2.2.4 on 2019-08-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('starter_time', models.TimeField(null=True, verbose_name='Başlangıç saati')),
                ('starter_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç günü')),
                ('size', models.IntegerField(default=0, null=True, verbose_name='Katılımcı sayısı')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Lokasyon')),
                ('category', models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('diğer', 'DİĞER'), ('yazılım', 'YAZILIM'), ('grafik tasarım', 'GRAFIK TASARIM')], max_length=53, null=True, verbose_name='Kategori')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
