# Generated by Django 2.2.8 on 2019-12-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='category',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='image',
        ),
        migrations.AddField(
            model_name='camp',
            name='cover_photo',
            field=models.CharField(max_length=250, null=True, verbose_name='cover_photo'),
        ),
        migrations.AddField(
            model_name='camp',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('yayında', 'Yayında'), ('başladı', 'Başladı'), ('bitti', 'Bitti')], default='yayında', max_length=53, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='campparticipants',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_participants', to='camp.Camp'),
        ),
        migrations.AlterField(
            model_name='campparticipants',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='IMG_4029.JPG', upload_to='camp/', verbose_name='resim')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='camp.Camp')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('point', models.SmallIntegerField(choices=[(None, 'Lütfen birini seçiniz'), (1, '(1) Çok Kötü'), (2, '(2) Kötü'), (3, '(3) Normal'), (4, '(4) İyi'), (5, '(5) Çok İyi')], verbose_name='Puan')),
                ('content', models.TextField()),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='camp.Camp')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_parent', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('icerik', models.TextField(max_length=1000, null=True, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
