# Generated by Django 2.2.4 on 2019-09-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campparticipants',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_participants', to='camp.Camp'),
        ),
        migrations.AlterField(
            model_name='campparticipants',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
