# Generated by Django 2.2.4 on 2019-09-05 13:56

import camp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_camp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, default='default/marijuana.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=camp.models.upload_to, verbose_name='Resim'),
        ),
    ]
