# Generated by Django 2.2.4 on 2019-09-14 14:04

import camp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20190910_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, default='IMG_4029.JPG', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=camp.models.upload_to, verbose_name='Resim'),
        ),
    ]
