# Generated by Django 2.2.4 on 2019-09-06 16:31

import camp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0003_camp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=camp.models.upload_to, verbose_name='Resim'),
        ),
        migrations.CreateModel(
            name='CampParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('camp', models.ForeignKey(null=True, on_delete=True, related_name='camp_participants', to='camp.Camp')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=True, related_name='camp_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kampa gelen katılımcılar',
            },
        ),
    ]
