# Generated by Django 2.2.4 on 2019-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20190914_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('yayında', 'Yayında'), ('başladı', 'Başladı'), ('bitti', 'Bitti')], max_length=53, null=True, verbose_name='Status'),
        ),
    ]
