# Generated by Django 2.2.4 on 2019-09-06 18:44

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_auto_20190906_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), null=True, srid=4326),
        ),
    ]
