# Generated by Django 2.2.4 on 2019-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_camp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='category',
        ),
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Seçiniz'), ('yayında', 'Yayında'), ('başladı', 'Başladı'), ('bitti', 'Bitti')], default='Yayında', max_length=53, null=True, verbose_name='Status'),
        ),
    ]
