# Generated by Django 2.2.4 on 2019-09-06 20:37

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_auto_20190906_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(40.0, 29.0), null=True, srid=4326),
        ),
    ]
