# Generated by Django 2.2.4 on 2019-09-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_auto_20190914_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='camp.Camp')),
            ],
        ),
    ]
