# Generated by Django 2.2.4 on 2019-09-06 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_auto_20190906_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
