# Generated by Django 2.2.4 on 2019-09-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='image',
        ),
    ]
