# Generated by Django 2.2.4 on 2019-09-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_camp_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='geometry',
        ),
    ]
