# Generated by Django 2.2.4 on 2019-09-19 18:41

import camp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_auto_20190919_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, default='IMG_4029.JPG', upload_to=camp.models.upload_to, verbose_name='resim'),
        ),
    ]
