# Generated by Django 2.2.4 on 2019-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_auto_20190919_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, default='IMG_4029.JPG', upload_to='camp/', verbose_name='resim'),
        ),
    ]
