# Generated by Django 2.2.4 on 2019-09-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0014_auto_20190922_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='camp.Camp'),
        ),
    ]
