# Generated by Django 2.2.4 on 2019-09-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_comment_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='camp',
        ),
    ]
