# Generated by Django 2.2.4 on 2019-10-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='star_point',
            field=models.FloatField(null=True, verbose_name='Yıldız Puanı'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='point',
            field=models.IntegerField(verbose_name='Puan'),
        ),
    ]
