# Generated by Django 2.2.4 on 2019-10-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0019_auto_20191011_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='star_point',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='point',
            field=models.SmallIntegerField(verbose_name='Puan'),
        ),
    ]
