# Generated by Django 2.2.4 on 2019-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0020_auto_20191011_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='point',
            field=models.SmallIntegerField(choices=[(None, 'Lütfen birini seçiniz'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Puan'),
        ),
    ]
