# Generated by Django 2.2.4 on 2019-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0021_auto_20191013_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='point',
            field=models.SmallIntegerField(choices=[(None, 'Lütfen birini seçiniz'), (1, '(1) Çok Kötü'), (2, '(2) Kötü'), (3, '(3) Normal'), (4, '(4) İyi'), (5, '(5) Çok İyi')], verbose_name='Puan'),
        ),
    ]
