# Generated by Django 2.2.4 on 2019-10-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_auto_20190930_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizer_score',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='organiztör puanı'),
        ),
    ]
