# Generated by Django 2.2.4 on 2019-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_userprofile_organizer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='star_point',
            field=models.FloatField(default=0, null=True, verbose_name='Yıldız Puanı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organizer_score',
            field=models.IntegerField(default=0, null=True, verbose_name='organiztör puanı'),
        ),
    ]
