# Generated by Django 2.2.8 on 2019-12-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organizer_score',
            field=models.IntegerField(default=0, null=True, verbose_name='organiztör puanı'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='star_point',
            field=models.FloatField(default=0, null=True, verbose_name='Yıldız Puanı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
