# Generated by Django 2.2.8 on 2020-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20191223_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='celery_id',
            field=models.CharField(max_length=255, null=True, verbose_name='celery_id'),
        ),
    ]
