# Generated by Django 2.2.4 on 2019-09-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('cover_photo', models.CharField(max_length=250, null=True, verbose_name='cover_photo')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Yazar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gönderiler',
                'ordering': ['-id'],
            },
        ),
    ]
