# Generated by Django 2.2.4 on 2019-09-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190924_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_photo',
        ),
    ]
