# Generated by Django 2.2.4 on 2019-09-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='unique_id',
        ),
    ]
